# This is a basic workflow to help you get started with Actions

name: Racknerd Updater

env:
  RACKNERD_REPO: racknerd

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-racknerd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: KarsonJo/racknerd-observer
          path: ${{ env.RACKNERD_REPO }}

      # Runs a single command using the runners shell
      - name: Run update script
        run: ${{ env.RACKNERD_REPO }}/main.py
