# This is a basic workflow to help you get started with Actions

name: Racknerd Updater

env:
  RACKNERD_REPO: racknerd
  MAIN_REPO: vps-data

# Controls when the workflow will run
on:
  schedule:
    - cron: 30 6,12,18 * * *
    - cron: 30 0 * * *
    - cron: 0 16 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      custom_param:
        description: Custom input parameter

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-racknerd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CheckOut Main
        uses: actions/checkout@v3
        with:
          path: ${{ env.MAIN_REPO }}

      # Checkout script repo
      - name: CheckOut Source
        uses: actions/checkout@v3
        with:
          repository: KarsonJo/racknerd-observer
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          path: ${{ env.RACKNERD_REPO }}

      # current time testing
      - name: Time Testing
        if: github.event.schedule == '0 16 * * *'
        run: echo "UTC 16:00"


      # Install Python & Cache
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      # Download Previous Artifact
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: racknerd-data-output
          path: ${{ env.RACKNERD_REPO }}
          
      # Run racknerd update script
      - name: Run update script
        run: |
          echo $custom_param
          cd ${{ env.RACKNERD_REPO }}
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py ${{ inputs.custom_param }}
          
      # save output as artifacts
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: racknerd-data-output
          path: ${{ env.RACKNERD_REPO }}/racknerd-list.json
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: racknerd-filtered-output
          path: ${{ env.RACKNERD_REPO }}/racknerd-filtered.json

      # update data by committing to this repo
      - name: Run commit script
        run: |
          cp ${{ env.RACKNERD_REPO }}/racknerd-filtered.json ${{ env.MAIN_REPO }}/racknerd-filtered.json
          cd ${{ env.MAIN_REPO }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add racknerd-filtered.json
          git commit -m "automatic update"
          git push
